// This file is automatically generated. Do not modify it manually.
// To update this file, regenerate it through the Firebase Studio connect flow.

import {type FirebaseOptions} from 'firebase/app';

/**
 * The Firebase configuration object.
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBRY1g62BDLrmzA6iW0xjm_cbFNjvPxXb8",
  authDomain: "invoiceflow-b6fbb.firebaseapp.com",
  projectId: "invoiceflow-b6fbb",
  storageBucket: "invoiceflow-b6fbb.appspot.com",
  messagingSenderId: "250376740940",
  appId: "1:250376740940:web:ebe3101cf8ed90bf6b94e9",
  measurementId: "G-N19ZZCBZLK"
};
