// This file is automatically generated. Do not modify it manually.
// To update this file, regenerate it through the Firebase Studio connect flow.

import {type FirebaseOptions} from 'firebase/app';

/**
 * The Firebase configuration object.
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
};
