import type { Expense } from '@/lib/types';
import { format } from 'date-fns';
import { Card } from './ui/card';
import Image from 'next/image';
import { formatCurrency } from '@/lib/utils';

type ExpensePreviewProps = {
  expense: Expense;
};

export default function ExpensePreview({ expense }: ExpensePreviewProps) {
  return (
    <Card className="w-[210mm] min-h-[275mm] mx-auto p-8 shadow-lg bg-white text-black relative text-lg">
      <div className="flex justify-between items-start mb-8">
        <div className="flex items-center gap-4">
          {/* Assuming a logo for the user/company, or a placeholder */}
          <Image src="/img/logo.png" alt="Company Logo" width={60} height={60} className="rounded-md object-cover" data-ai-hint="logo" />
          <div>
            <h1 className="text-3xl font-bold text-gray-800">PawSolutions</h1>
            {/* <p className="text-gray-600">For: {expense.user ? (expense.user.name || expense.user.email) : 'N/A'}</p> */}
          </div>
        </div>
        <div className="text-right">
          <h2 className="text-4xl font-bold uppercase text-gray-400">Expense</h2>
          <p className="text-gray-600 mt-2"># {expense.id}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div>
          <h3 className="text-base font-semibold text-gray-500 uppercase">Expense Details</h3>
          <div className="mt-2 text-gray-800">
            <p><strong>Item Name:</strong> {expense.itemName}</p>
            <p><strong>Vendor:</strong> {expense.vendor}</p>
            <p><strong>Category:</strong> {expense.category}</p>
            <p><strong>Purchase Date:</strong> {format(new Date(expense.purchaseDate), 'MMM d, yyyy')}</p>
          </div>
        </div>
        <div className="text-right">
          <h3 className="text-base font-semibold text-gray-500 uppercase">Amount</h3>
          <p className="text-4xl font-bold text-gray-800 mt-2">{formatCurrency(expense.amount)}</p>
          {expense.receiptUrl && (
            <div className="mt-4">
              <a href={expense.receiptUrl} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
                View Receipt
              </a>
            </div>
          )}
        </div>
      </div>

      {expense.description && (
        <div className="mt-8">
          <h4 className="text-base font-semibold text-gray-500 uppercase">Description</h4>
          <p className="text-base text-gray-600 mt-2">{expense.description}</p>
        </div>
      )}

      <footer className="absolute bottom-8 left-8 right-8 text-center text-xs text-gray-400">
        <p>Generated by PawBalance</p>
        <p>Expense ID: {expense.id}</p>
        <p>© 2025 PawSolutions Oy. All rights reserved.</p>
      </footer>
    </Card>
  );
}
